services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app

  postgres:
    image: 'postgres:17'
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
