"""permission_name_and_codename_unique

Revision ID: 00ee5bc67e81
Revises: 0c3a6487f283
Create Date: 2026-01-12 18:12:30.203623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ee5bc67e81'
down_revision: Union[str, Sequence[str], None] = '0c3a6487f283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_unique_constraint(None, 'permissions', ['codename'])
    op.create_unique_constraint(None, 'permissions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_table('role_permission')
    # ### end Alembic commands ###
