"""unique_together_for_coefficients

Revision ID: 033cda7dc4dd
Revises: aee2a9f1d527
Create Date: 2026-01-29 18:34:29.420758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033cda7dc4dd'
down_revision: Union[str, Sequence[str], None] = 'aee2a9f1d527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_building_coefficients_coefficient_id_name', 'building_coefficient_types', ['coefficient_id', 'name'])
    op.create_unique_constraint('uq_building_coefficients_building_id_name', 'building_coefficients', ['building_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_building_coefficients_building_id_name', 'building_coefficients', type_='unique')
    op.drop_constraint('uq_building_coefficients_coefficient_id_name', 'building_coefficient_types', type_='unique')
    # ### end Alembic commands ###
