"""apartment_coefficients_fks_cascade

Revision ID: 0a039b60af9b
Revises: f83d709a081b
Create Date: 2026-01-15 12:06:50.376410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a039b60af9b'
down_revision: Union[str, Sequence[str], None] = 'f83d709a081b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('apartment_coefficients_apartment_id_fkey'), 'apartment_coefficients', type_='foreignkey')
    op.drop_constraint(op.f('apartment_coefficients_coefficient_type_id_fkey'), 'apartment_coefficients', type_='foreignkey')
    op.create_foreign_key(None, 'apartment_coefficients', 'apartments', ['apartment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'apartment_coefficients', 'building_coefficient_types', ['coefficient_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apartment_coefficients', type_='foreignkey')
    op.drop_constraint(None, 'apartment_coefficients', type_='foreignkey')
    op.create_foreign_key(op.f('apartment_coefficients_coefficient_type_id_fkey'), 'apartment_coefficients', 'building_coefficient_types', ['coefficient_type_id'], ['id'])
    op.create_foreign_key(op.f('apartment_coefficients_apartment_id_fkey'), 'apartment_coefficients', 'apartments', ['apartment_id'], ['id'])
    # ### end Alembic commands ###
