"""initial

Revision ID: 0c3a6487f283
Revises: 
Create Date: 2026-01-12 13:52:58.675973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3a6487f283'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complexes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('codename', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('floor_count', sa.Integer(), nullable=False),
    sa.Column('base_count', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('price_unit', sa.String(length=10), nullable=False),
    sa.Column('maxCoefficient', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=256), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('area', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('room_count', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_coefficients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_coefficient_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('coefficient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coefficient_id'], ['building_coefficients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartment_coefficients',
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('coefficient_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['coefficient_type_id'], ['building_coefficient_types.id'], ),
    sa.PrimaryKeyConstraint('apartment_id', 'coefficient_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartment_coefficients')
    op.drop_table('building_coefficient_types')
    op.drop_table('building_coefficients')
    op.drop_table('apartments')
    op.drop_table('users')
    op.drop_table('buildings')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('complexes')
    # ### end Alembic commands ###
