"""apartment_building_id_not_nullable

Revision ID: 14918078314e
Revises: d20ea823d8d5
Create Date: 2026-01-14 10:48:54.681179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14918078314e'
down_revision: Union[str, Sequence[str], None] = 'd20ea823d8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartments', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartments', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
