"""empty message

Revision ID: 275f27ee181e
Revises: e6f39498fa9c
Create Date: 2026-02-10 11:49:48.943264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275f27ee181e'
down_revision: Union[str, Sequence[str], None] = 'e6f39498fa9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('role_permission_role_id_fkey'), 'role_permission', type_='foreignkey')
    op.drop_constraint(op.f('role_permission_permission_id_fkey'), 'role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permission', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.create_foreign_key(op.f('role_permission_permission_id_fkey'), 'role_permission', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key(op.f('role_permission_role_id_fkey'), 'role_permission', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
