"""apartment_status

Revision ID: 2bc2d7c5f5bc
Revises: 8a5cf5ff30fe
Create Date: 2026-02-09 18:48:45.549799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc2d7c5f5bc'
down_revision: Union[str, Sequence[str], None] = '8a5cf5ff30fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as NULLABLE
    op.add_column(
        'apartments',
        sa.Column('status', sa.String(length=100), nullable=True)
    )

    # 2. Fill existing rows
    op.execute(
        "UPDATE apartments SET status = 'built' WHERE status IS NULL"
    )

    # 3. Enforce NOT NULL + set DB default
    op.alter_column(
        'apartments',
        'status',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'status')
    # ### end Alembic commands ###
