"""user_fields*fullname_phone

Revision ID: 847eb5767049
Revises: 275f27ee181e
Create Date: 2026-02-26 17:12:49.309438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847eb5767049'
down_revision: Union[str, Sequence[str], None] = '275f27ee181e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###
