"""bct_bc_id_not_nullable

Revision ID: 8a5cf5ff30fe
Revises: 033cda7dc4dd
Create Date: 2026-01-30 19:22:02.891476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5cf5ff30fe'
down_revision: Union[str, Sequence[str], None] = '033cda7dc4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building_coefficient_types', 'coefficient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building_coefficient_types', 'coefficient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
