"""empty message

Revision ID: aee2a9f1d527
Revises: f3e05a548c88
Create Date: 2026-01-29 18:10:44.751702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee2a9f1d527'
down_revision: Union[str, Sequence[str], None] = 'f3e05a548c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building_coefficients', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('building_coefficients', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
