"""building_image_url

Revision ID: be2a1b06075d
Revises: 847eb5767049
Create Date: 2026-02-26 17:38:09.505928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2a1b06075d'
down_revision: Union[str, Sequence[str], None] = '847eb5767049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'image_url')
    # ### end Alembic commands ###
