"""building_4th_and_6th_fields

Revision ID: d20ea823d8d5
Revises: 00ee5bc67e81
Create Date: 2026-01-14 10:32:06.826926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20ea823d8d5'
down_revision: Union[str, Sequence[str], None] = '00ee5bc67e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('base_price', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('buildings', sa.Column('max_coefficient', sa.Numeric(precision=20, scale=2), nullable=False))
    op.drop_column('buildings', 'maxCoefficient')
    op.drop_column('buildings', 'base_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('base_count', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.add_column('buildings', sa.Column('maxCoefficient', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.drop_column('buildings', 'max_coefficient')
    op.drop_column('buildings', 'base_price')
    # ### end Alembic commands ###
