"""permission_label

Revision ID: e6f39498fa9c
Revises: 2bc2d7c5f5bc
Create Date: 2026-02-10 11:46:16.195467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f39498fa9c'
down_revision: Union[str, Sequence[str], None] = '2bc2d7c5f5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('label', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'permissions', ['label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_column('permissions', 'label')
    # ### end Alembic commands ###
