"""permission_name_deleted

Revision ID: f3e05a548c88
Revises: 04c68d926f3b
Create Date: 2026-01-18 15:20:11.649380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e05a548c88'
down_revision: Union[str, Sequence[str], None] = '04c68d926f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('permissions_name_key'), 'permissions', type_='unique')
    op.drop_column('permissions', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('permissions_name_key'), 'permissions', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
