"""building_complex_id_required

Revision ID: f83d709a081b
Revises: 14918078314e
Create Date: 2026-01-14 18:15:20.986908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83d709a081b'
down_revision: Union[str, Sequence[str], None] = '14918078314e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'complex_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buildings', 'complex_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
